"""empty message

Revision ID: 239b12f213d4
Revises: 5ae98efce3a1
Create Date: 2021-02-14 19:13:46.173970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239b12f213d4'
down_revision = '5ae98efce3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
